### PR TITLE
Add Host Resolver value

### PR DESCRIPTION
**Pull request by HomerITS**
A configurable Host Resolver field is required to override the ingestion
server URL when the ingestion server is different then the required
resolver server.

### CODE REVIEW

**Comment by jordandukart** [comment]
What's the use case for this? Also are you open to refining your pull request as you are including files that should be untracked, not complying to coding standards etc?

**Comment by HomerITS** [comment]
Hi Jordan,

The use case would be to provide the site administrator the ability to determine the Handle resolver host, which may differ from the host being used for ingestion.  We use multiple Islandora ingestion hosts in an effort to reduce the load on the host serving up pages for display.  For example, we have ingestion1.lib.uconn.edu [ server 1 ] and ingestion2.lib.uconn.edu  [ server 2 ] being used for batch ingestion and use display.lib.uconn.edu [ server 0 ] to server up the pages to the public.  The “host” form field would contain “display.lib.uconn.edu” and would override the default, which for the handle application, is to use the host being used for ingestion.

We use subversion at the UConn library and are somewhat GIT newbies so could you be more specific “are including files that should be untracked, not complying to coding standards etc.?”.  Are you referring to the gitgnore, etc., files?

Cheers,

Doug

**Comment by willtp87** [comment]
"are including files that should be untracked, not complying to coding standards etc."  The project files and git ignore shouldn't be included in the pull. Islandora has some useful [docs](https://github.com/Islandora/islandora/wiki#documentation-for-developers) on subjects like code standards and git practices.

**Comment by jordandukart** [comment]
Superceded by https://github.com/discoverygarden/islandora_handle/pull/12, closing.

**Pull request closed without merging**
